apiVersion: apps/v1
kind: Deployment
metadata: 
  name: aws9deploy
spec: 
  strategy:
    type: RollingUpdate
  replicas: 10
  selector:
    matchLabels:
      app: web    # (1)Pod 작성시 이 부분(label -> app: web)이 포함되어야 함
  template:   # 여기에서 부터 Pod 작성
    metadata:
      labels:
        app: web  # 반드시 (1) 과 동일해야 함
    spec:
      containers:
        - name: aws9ctn
          image: hikna92/aws9:green
---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc
spec:
  type: NodePort
  ports:
  - name: aws9-port
    port: 8080 #cluster-ip의 포트번호
    protocol: TCP
    targetPort: 80  #컨테이너의 포트
    nodePort: 30080 
  selector:
    app: web #pod의 label을 지정해 주어야한다.